version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/debian/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies"
      - "Lang: Dockerfile"
  - package-ecosystem: "docker"
    directory: "/alpine/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies"
      - "Lang: Dockerfile"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies"
      - "Lang: Python"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Type: Dependencies"
      - "Type: CI"
