name: Sync master branch and main branch
on:
  push:
    branches:
      - master
jobs:
  release-candidate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Setup remote repository
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git pull
      - name: Merge master branch into main branch
        run: |
          git checkout -b main origin/main
          git merge master --no-commit
      - name: Push update to main branch
        run: |
          git push origin main > /dev/null 2>&1
