name: Sync main branch and master branch
on:
  push:
    branches:
      - main
jobs:
  release-candidate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Setup remote repository
        run: |
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git pull
      - name: Merge main branch into master branch
        run: |
          git checkout -b master origin/master
          git merge main --no-commit
      - name: Push update to master branch
        run: |
          git push origin master > /dev/null 2>&1
